<?php
namespace SYS_ADMIN\controllers;

use yii\web\Controller;

class CommonController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}
